name: Zip and Upload to Release

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Zip the current directory (excluding .git and .github)
        run: |
          zip -r oreui-utilities.zip.mcpack . -x "*.git*" -x ".github/*"

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh auth setup-git
          gh auth status

      - name: Get the latest release tag
        id: get_release
        run: |
          LATEST_TAG=$(gh release view --json tagName -q '.tagName')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Upload zip to the latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$LATEST_TAG" oreui-utilities.zip.mcpack --repo faizul726/oreui-utilities --clobber
